# Generated by Django 3.2.7 on 2021-09-01 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('p', 'published'), ('d', 'draft')], max_length=1, verbose_name='وضعیت'),
        ),
    ]
