# Generated by Django 3.2.7 on 2021-09-08 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210902_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(related_name='category', to='blog.Category', verbose_name='دسته\u200cبندی'),
        ),
    ]
