# Generated by Django 3.2.7 on 2021-09-09 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان عکس')),
                ('photo', models.ImageField(upload_to='images', verbose_name='عکس')),
                ('caption', models.TextField(verbose_name='توضیحات')),
                ('time', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ ثبت')),
                ('photographer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='عکاس')),
            ],
        ),
    ]
